[book]
authors = ["watchakorn-18k"]
language = "en"
multilingual = false
src = "src"
title = "PPYTHON-BASIC"

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
