[book]
authors = ["watchakorn-18k"]
language = "th"
multilingual = false
src = "src"
title = "PPYTHON-BASIC"


[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.repl]
src = "https://mr-addict.github.io/mdbook-repl/embed/"
# python is disabled by default and loading is lazy
python.enable = true
python.loading = "lazy"

# typescript is disabled by default and loading is lazy
typescript.enable = true
typescript.loading = "lazy"

# javascript is disabled by default and loading is lazy
javascript.enable = true
javascript.loading = "lazy"

[output]

[output.html]
git-repository-url = "https://github.com/PpythonBasic"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
input-404 = "not-found.md"

[output.html.playground]
editable = true

[output.html.search]
enable = true
